@Library("dev-lib") _
def uname
def pwd
def strComment
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Dev pipeline'
            }
        }
                stage ("Update build status"){
            steps {
               script {
               
                 try {
                      buildInfra = true //input message: 'Is build successful', parameters: [[$class: 'ChoiceParameterDefinition', choices:'Yes\nNo', description: 'If build successful, click on Yes. Else, click on No', name: 'Build Successful?']]
                   }
                 catch (err) {
                      buildInfra = true
                 }
                 
              }
            }
        }
        stage ('lib call'){
            steps{
                 withCredentials([usernamePassword(credentialsId: 'phire_api_cred', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]){
                     script{
                     uname = env.USERNAME
                     pwd = env.USERPASS
                     
                     }
                 }
                 script{
                    strComment=PhireRequest(uname, pwd, PHIRE_NUM, TICKET_STATUS, ISSUE_ASSIGNEE, ISSUE_ASSIGNEE_EMAIL, 'S', TICKET_ID, LAST_COMMENT_BODY, REQUEST_USER, REQUEST_USER_EMAIL, 'http://140.238.207.38:8000//PSIGW/RESTListeningConnector/PSFT_HR/DEL_API_CR_NEXT_STEP.v1/')
                 }                /*def args2 =[
                    "userid":uname, "pswd":pwd, "phire_num":PHIRE_NUM, "tkt_status":TICKET_STATUS, "tkt_asgne":ISSUE_ASSIGNEE,
                    "tkt_asgn_email":ISSUE_ASSIGNEE_EMAIL, "mig_type": "S", "tkt_id": TICKET_ID, "tkt_lst_cmt":LAST_COMMENT_BODY,
                    "req_usr":REQUEST_USER, "req_email":REQUEST_USER_EMAIL,
                    "url":"http://140.238.207.38:8000//PSIGW/RESTListeningConnector/PSFT_HR/DEL_API_CR_NEXT_STEP.v1/"
                    ]
                PhireRequest(args2, jenkinsWorkflowScript:this)*/
            }                
            
        }
        stage ("Send back build status"){
            steps {
                script {
            if (buildInfra == 'Yes') 
                 {
                     echo 'buildInfra - Yes'
                //def fixedInBuild = [fields: [customfield_10011: 'Build is successful. Find additional comments in Comment Box']]
                //def transitionInput = [transition: [id: '61']]
                //jiraTransitionIssue idOrKey: JIRA_ISSUE_KEY, input: transitionInput, site: 'JIRA'
                //jiraEditIssue idOrKey: JIRA_ISSUE_KEY, issue: fixedInBuild, site: 'JIRA'
                //messaging = input message: 'Any additional comments?', parameters: [text(defaultValue: '', description: 'Enter any additional comments', name: 'COMMENT')]
                messaging = 'Phire step completed for ' + PHIRE_NUM
                //jiraAddComment comment: messaging, idOrKey: JIRA_ISSUE_KEY, site: 'JiraSSL'
                jiraAddComment comment: strComment, idOrKey: JIRA_ISSUE_KEY, site: 'JiraSSL'
                }
            else 
            {
                echo 'buildInfra - No'
                //def fixedInBuild = [fields: [customfield_10011: 'Build Failed. Find reasons in Comment Box']]
                def transitionInput = [transition: [id: '41']]
               // jiraTransitionIssue idOrKey: JIRA_ISSUE_KEY, input: transitionInput, site: 'JIRA'
               // jiraEditIssue idOrKey: JIRA_ISSUE_KEY, issue: fixedInBuild, site: 'JIRA'
                //messaging = input message: 'Why did the build fail?', parameters: [text(defaultValue: '', description: 'Enter reasons for build failure', name: 'COMMENT')]
                messaging = 'Phire step completed for ' + PHIRE_NUM
                jiraAddComment comment: strComment, idOrKey: JIRA_ISSUE_KEY, site: 'JiraSSL'
                println strComment
            }
           }       
          }
        }  
    }
}
