//@Library("test-lib") _
@Library("dev-lib") _
def uname
def pwd
def args
pipeline {
    agent any

    stages {
        stage ('Read Message'){
            steps{
                 withCredentials([usernamePassword(credentialsId: 'phire_api_cred', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]){
                     script{
                        uname = env.USERNAME
                        pwd = env.USERPASS
                     }
                 }
                 script{
                    //strComment=PhireRequest(uname, pwd, PHIRE_NUM, TICKET_STATUS, ISSUE_ASSIGNEE, ISSUE_ASSIGNEE_EMAIL, 'S', TICKET_ID, LAST_COMMENT_BODY, REQUEST_USER, REQUEST_USER_EMAIL, 'http://140.238.207.38:8000//PSIGW/RESTListeningConnector/PSFT_HR/DEL_API_CR_NEXT_STEP.v1/')
                    args=CommRequest(ticketid:JIRA_ISSUE_KEY, phire_domain:phi_domain, phire_cr:phi_cr, upd_ext:update_jira, assignee:asigneeId,assignee_email:asgnEmail, comment:commentTxt )
                 }                /*def args2 =[
                    "userid":uname, "pswd":pwd, "phire_num":PHIRE_NUM, "tkt_status":TICKET_STATUS, "tkt_asgne":ISSUE_ASSIGNEE,
                    "tkt_asgn_email":ISSUE_ASSIGNEE_EMAIL, "mig_type": "S", "tkt_id": TICKET_ID, "tkt_lst_cmt":LAST_COMMENT_BODY,
                    "req_usr":REQUEST_USER, "req_email":REQUEST_USER_EMAIL,
                    "url":"http://140.238.207.38:8000//PSIGW/RESTListeningConnector/PSFT_HR/DEL_API_CR_NEXT_STEP.v1/"
                    ]
                PhireRequest(args2, jenkinsWorkflowScript:this)*/
            }                
            
        }
        stage ("Update Jira"){
            steps {
                script {
                //def fixedInBuild = [fields: [customfield_10011: 'Build is successful. Find additional comments in Comment Box']]
                //def transitionInput = [transition: [id: '61']]
                //jiraTransitionIssue idOrKey: JIRA_ISSUE_KEY, input: transitionInput, site: 'JIRA'
                //jiraEditIssue idOrKey: JIRA_ISSUE_KEY, issue: fixedInBuild, site: 'JIRA'
                //messaging = input message: 'Any additional comments?', parameters: [text(defaultValue: '', description: 'Enter any additional comments', name: 'COMMENT')]
                //messaging = 'Phire step completed for ' + PHIRE_NUM
                //jiraAddComment comment: messaging, idOrKey: JIRA_ISSUE_KEY, site: 'JiraSSL'
                jiraAddComment comment: args.comment, idOrKey: JIRA_ISSUE_KEY, site: 'JiraSSL'
           }       
          }
        }  
    }
}
